// Copyright 2018-2026 the Deno authors. MIT license.

//! Rust bindings to libuv.
//!
//! This crate provides raw FFI bindings to libuv v1.51.0 (in the [`sys`]
//! module, generated by bindgen) plus safe Rust wrappers for the event
//! loop and common handle types.
//!
//! # Dropping down to raw FFI
//!
//! Every safe wrapper exposes an `as_mut_ptr()` method that returns the
//! underlying `sys::uv_*_t` pointer so you can call [`sys`] functions
//! directly.  Going the other direction, each type has an unsafe
//! `from_raw()` constructor that wraps an already-initialized raw pointer.

pub mod sys;

pub mod error;
pub mod handle;
pub mod loop_;

pub use error::UvError;
pub use handle::UvCheck;
pub use handle::UvIdle;
pub use handle::UvPrepare;
pub use handle::UvTimer;
pub use loop_::RunMode;
pub use loop_::UvLoop;

#[cfg(test)]
mod tests {
  use std::cell::Cell;
  use std::ffi::CStr;
  use std::mem::MaybeUninit;
  use std::rc::Rc;
  use std::sync::atomic::AtomicBool;
  use std::sync::atomic::AtomicI64;
  use std::sync::atomic::Ordering;

  use super::*;

  // =========================================================================
  // Raw binding tests (use sys::*)
  // =========================================================================

  #[test]
  fn test_version() {
    unsafe {
      let version = sys::uv_version();
      // libuv 1.51.0 = (1 << 16) | (51 << 8) | 0 = 78592
      assert_eq!(version, 78592);

      let version_str = sys::uv_version_string();
      let version_cstr = CStr::from_ptr(version_str);
      assert_eq!(version_cstr.to_str().unwrap(), "1.51.0");
    }
  }

  #[test]
  fn test_loop_init_close() {
    unsafe {
      let mut loop_: MaybeUninit<sys::uv_loop_t> = MaybeUninit::uninit();
      let result = sys::uv_loop_init(loop_.as_mut_ptr());
      assert_eq!(result, 0);

      let loop_ = loop_.assume_init_mut();
      let result = sys::uv_loop_close(loop_);
      assert_eq!(result, 0);
    }
  }

  #[test]
  fn test_default_loop() {
    unsafe {
      let loop_ = sys::uv_default_loop();
      assert!(!loop_.is_null());

      // Check the loop is alive initially (no handles)
      let alive = sys::uv_loop_alive(loop_);
      assert_eq!(alive, 0); // No handles, so not "alive"
    }
  }

  #[test]
  fn test_error_strings() {
    unsafe {
      // Test error name for ENOENT (uv_errno_t_UV_ENOENT = -2)
      let err_name = sys::uv_err_name(sys::uv_errno_t_UV_ENOENT);
      let err_cstr = CStr::from_ptr(err_name);
      assert_eq!(err_cstr.to_str().unwrap(), "ENOENT");

      // Test error string for ENOENT
      let err_str = sys::uv_strerror(sys::uv_errno_t_UV_ENOENT);
      let err_cstr = CStr::from_ptr(err_str);
      assert!(err_cstr.to_str().unwrap().contains("no such file"));
    }
  }

  /// Counter for idle callback test
  static IDLE_COUNTER: AtomicI64 = AtomicI64::new(0);

  /// Callback for idle handle - stops after 1000 iterations
  unsafe extern "C" fn idle_callback(handle: *mut sys::uv_idle_t) {
    let count = IDLE_COUNTER.fetch_add(1, Ordering::SeqCst) + 1;
    if count >= 1000 {
      unsafe { sys::uv_idle_stop(handle) };
    }
  }

  /// Close callback - does nothing, just needed for uv_close
  unsafe extern "C" fn close_cb(_handle: *mut sys::uv_handle_t) {}

  /// Test based on the libuv idle example from the docs
  #[test]
  fn test_idle_example() {
    IDLE_COUNTER.store(0, Ordering::SeqCst);

    unsafe {
      let mut loop_: MaybeUninit<sys::uv_loop_t> = MaybeUninit::uninit();
      let result = sys::uv_loop_init(loop_.as_mut_ptr());
      assert_eq!(result, 0);
      let loop_ = loop_.as_mut_ptr();

      let mut idler: MaybeUninit<sys::uv_idle_t> = MaybeUninit::uninit();
      let result = sys::uv_idle_init(loop_, idler.as_mut_ptr());
      assert_eq!(result, 0);

      let result = sys::uv_idle_start(idler.as_mut_ptr(), Some(idle_callback));
      assert_eq!(result, 0);

      // Run the loop
      let result = sys::uv_run(loop_, sys::uv_run_mode_UV_RUN_DEFAULT);
      assert_eq!(result, 0);

      // Verify the callback ran the expected number of times
      assert_eq!(IDLE_COUNTER.load(Ordering::SeqCst), 1000);

      // Close the idle handle before closing the loop
      sys::uv_close(
        idler.as_mut_ptr() as *mut sys::uv_handle_t,
        Some(close_cb),
      );
      // Run loop again to process the close
      sys::uv_run(loop_, sys::uv_run_mode_UV_RUN_DEFAULT);

      // Clean up
      let result = sys::uv_loop_close(loop_);
      assert_eq!(result, 0);
    }
  }

  static TIMER_FIRED: AtomicBool = AtomicBool::new(false);

  unsafe extern "C" fn timer_callback(_handle: *mut sys::uv_timer_t) {
    TIMER_FIRED.store(true, Ordering::SeqCst);
  }

  #[test]
  fn test_timer() {
    TIMER_FIRED.store(false, Ordering::SeqCst);

    unsafe {
      let mut loop_: MaybeUninit<sys::uv_loop_t> = MaybeUninit::uninit();
      let result = sys::uv_loop_init(loop_.as_mut_ptr());
      assert_eq!(result, 0);
      let loop_ = loop_.as_mut_ptr();

      let mut timer: MaybeUninit<sys::uv_timer_t> = MaybeUninit::uninit();
      let result = sys::uv_timer_init(loop_, timer.as_mut_ptr());
      assert_eq!(result, 0);

      // Start timer with 1ms timeout, no repeat
      let result =
        sys::uv_timer_start(timer.as_mut_ptr(), Some(timer_callback), 1, 0);
      assert_eq!(result, 0);

      // Run the loop
      let result = sys::uv_run(loop_, sys::uv_run_mode_UV_RUN_DEFAULT);
      assert_eq!(result, 0);

      assert!(TIMER_FIRED.load(Ordering::SeqCst));

      // Close the timer handle before closing the loop
      sys::uv_close(
        timer.as_mut_ptr() as *mut sys::uv_handle_t,
        Some(close_cb),
      );
      // Run loop again to process the close
      sys::uv_run(loop_, sys::uv_run_mode_UV_RUN_DEFAULT);

      let result = sys::uv_loop_close(loop_);
      assert_eq!(result, 0);
    }
  }

  #[test]
  fn test_handle_sizes() {
    unsafe {
      // Verify handle sizes are non-zero and reasonable
      let tcp_size = sys::uv_handle_size(sys::uv_handle_type_UV_TCP);
      assert!(tcp_size > 0);

      let timer_size = sys::uv_handle_size(sys::uv_handle_type_UV_TIMER);
      assert!(timer_size > 0);

      let idle_size = sys::uv_handle_size(sys::uv_handle_type_UV_IDLE);
      assert!(idle_size > 0);

      let req_size = sys::uv_req_size(sys::uv_req_type_UV_WRITE);
      assert!(req_size > 0);
    }
  }

  // =========================================================================
  // Safe wrapper tests
  // =========================================================================

  #[test]
  fn test_safe_loop() {
    let lp = UvLoop::new().unwrap();
    assert!(!lp.alive());
    // Run with no handles — should return immediately.
    let still_active = lp.run(RunMode::Default);
    assert!(!still_active);
  }

  #[test]
  fn test_safe_idle() {
    let lp = UvLoop::new().unwrap();
    let idle = UvIdle::new(&lp).unwrap();

    let counter = Rc::new(Cell::new(0u64));
    let cnt = Rc::clone(&counter);

    idle
      .start(move || {
        cnt.set(cnt.get() + 1);
        if cnt.get() >= 1000 {
          // We need to stop from outside, but the callback doesn't have
          // direct access to `idle`.  Use the loop's stop instead.
          // The idle handle will still be active, but the loop will exit.
        }
      })
      .unwrap();

    // Run the loop for a bounded number of iterations via RunMode::NoWait
    // in a manual loop so we don't spin forever.
    for _ in 0..2000 {
      lp.run(RunMode::NoWait);
      if counter.get() >= 1000 {
        break;
      }
    }

    assert!(counter.get() >= 1000);

    idle.stop().unwrap();
    idle.close();
    // Process the close callback.
    lp.run(RunMode::Default);
  }

  #[test]
  fn test_safe_timer() {
    let lp = UvLoop::new().unwrap();
    let timer = UvTimer::new(&lp).unwrap();

    let fired = Rc::new(Cell::new(false));
    let f = Rc::clone(&fired);

    timer.start(move || f.set(true), 1, 0).unwrap();

    lp.run(RunMode::Default);
    assert!(fired.get());

    timer.close();
    lp.run(RunMode::Default);
  }

  #[test]
  fn test_safe_prepare_check() {
    let lp = UvLoop::new().unwrap();

    // We use a shared Vec to record the order of callbacks.
    let order: Rc<Cell<Vec<&'static str>>> = Rc::new(Cell::new(Vec::new()));

    let prepare = UvPrepare::new(&lp).unwrap();
    let check = UvCheck::new(&lp).unwrap();

    // We also need a timer to make the loop do something (otherwise prepare
    // and check may not fire at all since there's no I/O to poll for).
    let timer = UvTimer::new(&lp).unwrap();

    let o1 = Rc::clone(&order);
    prepare
      .start(move || {
        let mut v = o1.take();
        v.push("prepare");
        o1.set(v);
      })
      .unwrap();

    let o2 = Rc::clone(&order);
    check
      .start(move || {
        let mut v = o2.take();
        v.push("check");
        o2.set(v);
      })
      .unwrap();

    // Fire once after 1ms so the loop has work to do.  The timer
    // callback stops the loop so that `run` returns (prepare/check
    // handles would otherwise keep it alive forever).
    let lp2 = Rc::clone(&lp);
    timer.start(move || lp2.stop(), 1, 0).unwrap();

    lp.run(RunMode::Default);

    let result = order.take();
    // There should be at least one prepare and one check.
    assert!(result.contains(&"prepare"), "prepare callback never fired");
    assert!(result.contains(&"check"), "check callback never fired");

    // In every loop iteration prepare comes before check.  Verify the
    // first prepare appears before the first check.
    let first_prepare = result.iter().position(|s| *s == "prepare").unwrap();
    let first_check = result.iter().position(|s| *s == "check").unwrap();
    assert!(
      first_prepare < first_check,
      "prepare should fire before check"
    );

    prepare.stop().unwrap();
    check.stop().unwrap();
    prepare.close();
    check.close();
    timer.close();
    lp.run(RunMode::Default);
  }
}
