// Copyright 2018-2026 the Deno authors. MIT license.

//! Raw FFI bindings to libuv, generated by bindgen.
//!
//! These are the unmodified C types and functions. Use the safe wrappers
//! in the parent module for most purposes; drop down to this module when
//! you need direct FFI access.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
